name: CI/CD

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "${{ github.repository }}"
          echo "${{ github.workspace }}"
          
          

  # This workflow contains a job called "deployment"
  deployment:
    runs-on: windows-latest
    environment: 
      name: Dev
    steps:
      - name: Deploy to Dev environment
        run: |
         echo "Deployment to Dev environment"
         echo "${{ vars.ENV }}"
         echo ${{ github.workspace }}
         echo "${{ vars.USER_NAME }}"
         echo "${{ vars.ARTIFACTS_PATH }}"
         echo "${{ secrets.USER_NAME }}"
         echo "${{ secrets.PASSWORD }}"
         echo "${{ secrets.HOSTNAME }}"
         &"${{ github.workspace }}\.github\workflows\test.ps1" "vamshi" "karre"
         
